name: yomuyomu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  archive: ^3.3.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  file_picker: ^10.1.2
  permission_handler: ^11.0.0
  device_info_plus: ^10.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.5
  uuid: ^4.5.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.8
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_user_pfp.png
    - assets/images/app_icon.png
    - assets/terms_conditions.txt
