// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9TIl2TaneipQasCdWsh5-rj_YQp6dfg',
    appId: '1:1018729185356:web:c338365107206cf1a834e9',
    messagingSenderId: '1018729185356',
    projectId: 'yomuyomu-40bd6',
    authDomain: 'yomuyomu-40bd6.firebaseapp.com',
    storageBucket: 'yomuyomu-40bd6.firebasestorage.app',
    measurementId: 'G-6J6PR5TW9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjBb8Q1Va_pKgaJHyrjccDhPT3dVcroy8',
    appId: '1:1018729185356:android:47506c9b8919167ea834e9',
    messagingSenderId: '1018729185356',
    projectId: 'yomuyomu-40bd6',
    storageBucket: 'yomuyomu-40bd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaXu3_LDZZi8EnW6hfFUqMpCc14qa25E',
    appId: '1:1018729185356:ios:fe551b8148a813a4a834e9',
    messagingSenderId: '1018729185356',
    projectId: 'yomuyomu-40bd6',
    storageBucket: 'yomuyomu-40bd6.firebasestorage.app',
    iosBundleId: 'com.example.yomuyomu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaXu3_LDZZi8EnW6hfFUqMpCc14qa25E',
    appId: '1:1018729185356:ios:fe551b8148a813a4a834e9',
    messagingSenderId: '1018729185356',
    projectId: 'yomuyomu-40bd6',
    storageBucket: 'yomuyomu-40bd6.firebasestorage.app',
    iosBundleId: 'com.example.yomuyomu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE9TIl2TaneipQasCdWsh5-rj_YQp6dfg',
    appId: '1:1018729185356:web:be7da27cf5f8dd33a834e9',
    messagingSenderId: '1018729185356',
    projectId: 'yomuyomu-40bd6',
    authDomain: 'yomuyomu-40bd6.firebaseapp.com',
    storageBucket: 'yomuyomu-40bd6.firebasestorage.app',
    measurementId: 'G-0HBD1DV6LX',
  );

}